"""initial schema

Revision ID: 9d54f6a1a0f6
Revises: 
Create Date: 2026-06-24 14:46:13.365803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d54f6a1a0f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('games_product_id_locale_key'), 'games', type_='unique')
    op.drop_index(op.f('idx_games_name'), table_name='games')
    op.drop_index(op.f('idx_games_discount'), table_name='games')
    op.create_index('idx_games_discount', 'games', ['discount_percent'], unique=False)
    op.create_index('idx_games_name_lower', 'games', [sa.literal_column("lower('name')")], unique=False)
    op.create_unique_constraint('uq_games_product_locale', 'games', ['product_id', 'locale'])
    op.drop_index(op.f('idx_price_history_game_checked'), table_name='price_history')
    op.create_index('idx_price_history_game_checked', 'price_history', ['game_id', 'checked_at'], unique=False)
    op.drop_constraint(op.f('user_notification_emails_user_id_email_key'), 'user_notification_emails', type_='unique')
    op.create_unique_constraint('uq_user_notification_emails_user_email', 'user_notification_emails', ['user_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_notification_emails_user_email', 'user_notification_emails', type_='unique')
    op.create_unique_constraint(op.f('user_notification_emails_user_id_email_key'), 'user_notification_emails', ['user_id', 'email'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_price_history_game_checked', table_name='price_history')
    op.create_index(op.f('idx_price_history_game_checked'), 'price_history', ['game_id', sa.literal_column('checked_at DESC')], unique=False)
    op.drop_constraint('uq_games_product_locale', 'games', type_='unique')
    op.drop_index('idx_games_name_lower', table_name='games')
    op.drop_index('idx_games_discount', table_name='games')
    op.create_index(op.f('idx_games_discount'), 'games', [sa.literal_column('discount_percent DESC')], unique=False)
    op.create_index(op.f('idx_games_name'), 'games', [sa.literal_column('lower(name)')], unique=False)
    op.create_unique_constraint(op.f('games_product_id_locale_key'), 'games', ['product_id', 'locale'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
